user:
  name: "Tomáš"
  language: "cs"

# ========================================
# LOCATION (MANUAL - Radkov)
# ========================================
location:
  auto_detect: false  # Vypnuto auto-detect

  # Manual location
  manual:
    city: "Radkov"
    region: "Moravskoslezský kraj"
    country: "Česká republika"
    timezone: "Europe/Prague"

  # Fallback (když by manual selhal)
  fallback:
    city: "Praha"
    country: "Česká republika"
    timezone: "Europe/Prague"

preferences:
  temperature_unit: "celsius"
  time_format: "24h"

# ========================================
# AI ASSISTANT CONFIGURATION
# ========================================
assistant:
  name: "Alexa"
  personality: "přátelský"
  response_style: "stručný"
  tone: "casual"
  wake_word: "Alexa"
  wake_word_threshold: 0.5

  rules:
    max_sentences: 3
    use_emoji: false
    formality: "ty"

  system_prompt: |
    Jsi {name}, hlasový asistent pro {user_name}.
    
    OSOBNOST:
    - {personality}, {tone}
    - Odpovídáš {response_style}, max {max_sentences} větami
    
    KONTEXT:
    Uživatel: {user_name}
    Poloha: {city}, {country}
    Čas: {current_time}
    Datum: {current_date}

# ========================================
# MODEL CONFIGURATION
# ========================================
models:
  cloud:
    provider: "openai"
    model: "gpt-4o-mini"
    temperature: 0.7
    max_tokens: 150
    streaming: true

    # Performance tuning
    internet_check_timeout: 3.0      # Timeout pro internet check (sekundy)
    internet_cache_duration: 60      # Cache internet check (sekundy)
    max_retries: 3                   # Max počet retry pokusů

  local:
    provider: "ollama"
    model: "llama3.2:3b"
    temperature: 0.7
    max_tokens: 150
    url: "http://localhost:11434"
    timeout: 15.0                    # Request timeout (sekundy)

# ========================================
# ROUTING STRATEGY
# ========================================
routing:
  strategy: "intelligent"

  use_local_for:
    - "time_queries"
    - "date_queries"
    - "simple_calculations"

  use_cloud_for:
    - "complex_reasoning"
    - "creative_tasks"
    - "knowledge_queries"

  thresholds:
    local_confidence: 0.8
    max_local_time: 2.0

# ========================================
# AUDIO CONFIGURATION
# ========================================
audio:
  sample_rate: 16000
  channels: 1
  chunk_size: 1280
  gain: 6.0

  wake_word_models:
    - "alexa"

  stt:
    primary: "groq"
    fallback: "whisper"
    whisper_model: "small"
    language: "cs"

    # STT Advanced Configuration
    groq_model: "whisper-large-v3-turbo"     # Groq Whisper model
    deepgram_model: "nova-2"                 # Deepgram model
    deepgram_timeout: 40.0                   # Deepgram request timeout (sekundy)
    max_retries: 3                           # Max retry attempts pro všechny STT

    # Whisper Specific Settings
    whisper_beam_size: 1                     # Beam size (1 = fastest, 5 = better quality)
    whisper_vad_filter: true                 # Voice Activity Detection (remove silence)
